Repository BurkovskayaAD/FE94, pull requests merged in 2022-11, with the labels that each got.

#1 My first pull request
  hw_1.js
Labels: ready for review

#2 My first pull request
  hw_1.js
Labels: ready for review

#4 My first pull request
  hw_1.js
Labels: ready for review

#6 My first pull request
  hw_1.js
Labels: ready for review

#7 My first pull request
  hw_1.js
Labels: ready for review

#8 My first pull request
  hw_1.js
Labels: ready for review

#9 My first pull request
  hw_1.js
Labels: ready for review

#10 My first pull request
  hw_1.js
Labels: ready for review

#11 init(hw_1): start course Javascript Basic
  hw_1.js
Labels: ready for review

#14 My first pull request
  hw_1.js
Labels: ready for review

#15 Homework 2 Javascript Basic
  hw_2.js
  index.html
Labels: ready for review

#16 home work JS_2
  hw_1.js
  index.html
  js/hw_2.js
Labels: ready for review

#17 Homework 3 Javascript Basic
  hw_3/hw_3.js
  hw_3/index.html
Labels: ready for review

#18 My first pull request
  hw_1.js
Labels: ready for review

#19 init(hw_2)
  hw_2/index.html
  hw_2/script.js
Labels: ready for review

#21 JS variables
  hw_2.html
  hw_2.js
Labels: ready for review

#22 init(hw_2): start course Javascript
  hw_2/index.html
  hw_2/script.js
Labels: ready for review

#25 My first pull request
  hw_1.js
Labels: ready for review

#26 init(hw_3): Base of Javascript
  hw_3/index.html
  hw_3/script.js
Labels: ready for review

#27 hw_2
  hw_2/index.html
  hw_2/script.js
Labels: ready for review

#13 add hw_2
  Bobkov-hw_2/index.html
  Bobkov-hw_2/script.js
Labels: question, need to fix

#28 init(hw_1): start course Javascript Basic
  hw_1/hw_1.js
Labels: ready for review

#29 init(hw-2): Javascript Basic
  hw-2/hw-2.js
  hw-2/index.html
Labels: ready for review

#30 init(hw_3):start course Javascript
  .gitignore
  hw_3/index.html
  hw_3/main.js
Labels: ready for review

#34 init(hw_2): add solutions for tasks
  hw_2.js
  index.html
Labels: ready for review

#35 init(hw_3): Javascript Basic hw_3
  hw_3/hw_3.js
  hw_3/index.html
Labels: ready for review

#36 init(hw_2): home work 2 Javascript
  hw_2/index.html
  hw_2/src/hw_2.js
Labels: ready for review

#37 init(hw_2, hw_3): add solution for tasks
  Makushkina-hw_2/index.html
  Makushkina-hw_2/script.js
  Makushkina-hw_3/index.html
  Makushkina-hw_3/script.js
Labels: need to fix, ready for review
